# Describes the format for available Wink services
pair_new_device:
  name: Pair new device
  description: Pair a new device to a Wink Hub.
  fields:
    hub_name:
      name: Hub name
      description: The name of the hub to pair a new device to.
      required: true
      example: "My hub"
      selector:
        text:
    pairing_mode:
      name: Pairing mode
      description: Mode.
      required: true
      selector:
        select:
          options:
            - 'bluetooth'
            - 'kidde'
            - 'lutron'
            - 'zigbee'
            - 'zwave'
            - 'zwave_exclusion'
            - 'zwave_network_rediscovery'
    kidde_radio_code:
      name: Kidde radio code
      description: "A string of 8 1s and 0s one for each dip switch on the kidde device left --> right = 1 --> 8. Down = 1 and Up = 0"
      example: "10101010"
      selector:
        text:

rename_wink_device:
  name: Rename wink device
  description: Rename the provided device.
  target:
    entity:
      integration: wink
  fields:
    name:
      name: Name
      description: The name to change it to.
      required: true
      example: back_door
      selector:
        text:

delete_wink_device:
  name: Delete wink device
  description: Remove/unpair device from Wink.
  target:
    entity:
      integration: wink

pull_newly_added_devices_from_wink:
  name: Pull newly added devices from wink
  description: Pull newly paired devices from Wink.

refresh_state_from_wink:
  name: Refresh state from wink
  description: Pull the latest states for every device.

set_siren_volume:
  name: Set siren volume
  description: Set the volume of the siren for a Dome siren/chime.
  target:
    entity:
      integration: wink
      domain: switch
  fields:
    volume:
      name: Volume
      description: Volume level.
      required: true
      selector:
        select:
          options:
            - 'low'
            - 'medium'
            - 'high'

enable_chime:
  name: Enable chime
  description: Enable the chime of a Dome siren with the provided sound.
  target:
    entity:
      integration: wink
      domain: switch
  fields:
    tone:
      name: Tone
      description: >-
        The tone to use for the chime.
      required: true
      selector:
        select:
          options:
            - 'alert'
            - 'beep'
            - 'beep_beep'
            - 'doorbell'
            - 'doorbell_extended'
            - 'evacuation'
            - 'fur_elise'
            - 'inactive'
            - 'police_siren'
            - 'rondo_alla_turca'
            - 'william_tell'

set_siren_tone:
  name: Set siren tone
  description: Set the sound to use when the siren is enabled. (This doesn't enable the siren)
  target:
    entity:
      integration: wink
      domain: switch
  fields:
    tone:
      name: Tone
      description: >-
        The tone to use for the chime.
      required: true
      selector:
        select:
          options:
            - 'alert'
            - 'beep'
            - 'beep_beep'
            - 'doorbell'
            - 'doorbell_extended'
            - 'evacuation'
            - 'fur_elise'
            - 'inactive'
            - 'police_siren'
            - 'rondo_alla_turca'
            - 'william_tell'

siren_set_auto_shutoff:
  name: Siren set auto shutoff
  description: How long to sound the siren before turning off.
  target:
    entity:
      integration: wink
      domain: switch
  fields:
    auto_shutoff:
      name: Auto shutoff
      description: >-
        The time in seconds to sound the siren. (None and -1 are forever. Use None for gocontrol, and -1 for Dome)
      required: true
      selector:
        select:
          options:
            - 'None'
            - '-1'
            - '30'
            - '60'
            - '120'

set_siren_strobe_enabled:
  name: Set siren strobe enabled
  description: Enable or disable the strobe light when the siren is sounding.
  target:
    entity:
      integration: wink
      domain: switch
  fields:
    enabled:
      name: Enabled
      description: "True or False"
      required: true
      selector:
        boolean:

set_chime_strobe_enabled:
  name: Set chime strobe enabled
  description: Enable or disable the strobe light when the chime is sounding.
  target:
    entity:
      integration: wink
      domain: switch
  fields:
    enabled:
      name: Enabled
      description: "True or False"
      required: true
      selector:
        boolean:

enable_siren:
  name: Enable siren
  description: Enable/disable the siren.
  target:
    entity:
      integration: wink
      domain: switch
  fields:
    enabled:
      name: Enabled
      description: "true or false"
      required: true
      selector:
        boolean:

set_chime_volume:
  name: Set chime volume
  description: Set the volume of the chime for a Dome siren/chime.
  target:
    entity:
      integration: wink
      domain: switch
  fields:
    volume:
      name: Volume
      description: Volume level.
      required: true
      selector:
        select:
          options:
            - 'low'
            - 'medium'
            - 'high'

set_nimbus_dial_configuration:
  name: Set nimbus dial configuration
  description: Set the configuration of an individual nimbus dial
  target:
    entity:
      integration: wink
      domain: switch
  fields:
    rotation:
      name: Rotation
      description: Direction dial hand should spin.
      selector:
        select:
          options:
            - 'cw'
            - 'ccw'
    ticks:
      name: Ticks
      description: Number of times the hand should move
      selector:
        number:
          min: 0
          max: 3600
    scale:
      name: Scale
      description: How the dial should move in response to higher values.
      selector:
        select:
          options:
            - 'linear'
            - 'log'
    min_value:
      name: minimum value
      description: The minimum value allowed to be set
      example: 0
      selector:
        text:
    max_value:
      name: Maximum value
      description: The maximum value allowed to be set
      example: 500
      selector:
        text:
    min_position:
      name: Minimum position
      description: The minimum position the dial hand can rotate to generally.
      selector:
        number:
          min: 0
          max: 360
    max_position:
      name: Maximum position
      description: The maximum position the dial hand can rotate to generally.
      selector:
        number:
          min: 0
          max: 360

set_nimbus_dial_state:
  name: Set nimbus dial state
  description: Set the value and labels of an individual nimbus dial
  target:
    entity:
      integration: wink
  fields:
    value:
      name: Value
      description: The value that should be set (Should be between min_value and max_value)
      required: true
      example: 250
      selector:
        text:
    labels:
      name: Labels
      description: >-
        The values shown on the dial labels ["Dial 1", "test"] the first value
        is what is shown by default the second value is shown when the nimbus is
        pressed.
      example: ["example", "test"]
      selector:
        object:

set_lock_vacation_mode:
  name: Set lock vacation mode
  description: Set vacation mode for all or specified locks. Disables all user codes.
  fields:
    entity_id:
      name: Entity
      description: Name of lock to unlock.
      selector:
        entity:
          integration: wink
          domain: lock
    enabled:
      name: Enabled
      description: enable or disable. true or false.
      required: true
      selector:
        boolean:

set_lock_alarm_mode:
  name: Set lock alarm mode
  description: Set alarm mode for all or specified locks.
  fields:
    entity_id:
      name: Entity
      description: Name of lock to unlock.
      selector:
        entity:
          integration: wink
          domain: lock
    mode:
      name: Mode
      description: Select mode.
      required: true
      selector:
        select:
          options:
            - 'activity'
            - 'forced_entry'
            - 'tamper'

set_lock_alarm_sensitivity:
  name: Set lock alarm sensitivity
  description: Set alarm sensitivity for all or specified locks.
  fields:
    entity_id:
      name: Entity
      description: Name of lock to unlock.
      selector:
        entity:
          integration: wink
          domain: lock
    sensitivity:
      name: Sensitivity
      description: Choose the sensitivity.
      required: true
      selector:
        select:
          options:
            - 'low'
            - 'medium_low'
            - 'medium'
            - 'medium_high'
            - 'high'

set_lock_alarm_state:
  name: Set lok alarm state
  description: Set alarm state.
  fields:
    entity_id:
      name: Entity
      description: Name of lock to unlock.
      selector:
        entity:
          integration: wink
          domain: lock
    enabled:
      name: Enabled
      description: enable or disable.
      required: true
      selector:
        boolean:

set_lock_beeper_state:
  name: Set lock beeper state
  description: Set beeper state.
  fields:
    entity_id:
      name: Entity
      description: Name of lock to unlock.
      selector:
        entity:
          integration: wink
          domain: lock
    enabled:
      name: Enabled
      description: enable or disable.
      required: true
      selector:
        boolean:

add_new_lock_key_code:
  name: Add new lock key code
  description: Add a new user key code.
  fields:
    entity_id:
      name: Entity
      description: Name of lock to unlock.
      selector:
        entity:
          integration: wink
          domain: lock
    name:
      name: Name
      description: name of the new key code.
      required: true
      example: Bob
      selector:
        text:
    code:
      name: Code
      description: new key code, length must match length of other codes. Default length is 4.
      required: true
      example: 1234
      selector:
        text:
